import Link from 'next/link';

const siteUrl = 'https://www.revupmedia.co';
const bookingUrl = 'https://calendly.com/agha-abdulqadir2005/30min';

const faqs = [
  { question: 'What is ecommerce email marketing?', answer: 'Ecommerce email marketing is the practice of using permission-based email to help customers discover products, make a purchase, get more value after buying and return when there is a relevant reason to do so.' },
  { question: 'Which email automations matter most for ecommerce?', answer: 'The best starting point depends on the store, but welcome, cart, browse, post-purchase and win-back journeys are commonly reviewed first because they map to clear customer moments.' },
  { question: 'How do email campaigns differ from flows?', answer: 'Campaigns are planned sends for a particular launch, offer or story. Flows are automated messages triggered by a customer action or stage in the lifecycle. A healthy program uses both.' },
  { question: 'How do I improve ecommerce email marketing without sending more?', answer: 'Start by making messages more relevant: tighten segmentation, clarify the offer, improve the customer journey and review what each send is meant to accomplish before increasing frequency.' },
];

export function EcommerceEmailMarketingGuide() {
  const url = `${siteUrl}/guides/ecommerce-email-marketing-strategy`;
  const schema = { '@context': 'https://schema.org', '@graph': [
    { '@type': 'Article', headline: 'Ecommerce Email Marketing Strategy: A Practical Guide', description: 'A practical ecommerce email marketing guide covering lifecycle automation, campaigns, segmentation, list growth and measurement.', mainEntityOfPage: url, author: { '@id': `${siteUrl}/#organization` }, publisher: { '@id': `${siteUrl}/#organization` }, dateModified: '2026-09-23' },
    { '@type': 'FAQPage', mainEntity: faqs.map((faq) => ({ '@type': 'Question', name: faq.question, acceptedAnswer: { '@type': 'Answer', text: faq.answer } })) },
    { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: siteUrl }, { '@type': 'ListItem', position: 2, name: 'Guides' }, { '@type': 'ListItem', position: 3, name: 'Ecommerce Email Marketing Strategy', item: url }] },
  ] };
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <header className="site-header"><div className="container nav-shell"><Link className="brand" href="/"><img src="/assets/revup-logo.png" alt="RevUp Media" /><span>REVUP <span>MEDIA</span></span></Link><nav className="desktop-nav" aria-label="Primary navigation"><Link href="/">Home</Link><Link href="/services">Services</Link><Link href="/case-studies">Case Studies</Link><Link href="/about">About</Link></nav><a className="btn btn-primary btn-small nav-action" href={bookingUrl} target="_blank" rel="noopener">Book Free Audit <span className="arrow">→</span></a></div></header>
    <main className="service-page"><article><section className="service-hero"><div className="container"><p className="eyebrow">Ecommerce email marketing guide</p><h1>Ecommerce email marketing strategy: a practical guide</h1><p className="service-lead">A useful retention program is not a bigger sending calendar. It is a clearer customer journey: the right message, for the right person, at a moment when it can genuinely help.</p></div></section>
      <section className="section service-section"><div className="container guide-copy"><p className="eyebrow">The foundation</p><h2>Build around the customer journey, not a template library.</h2><p>Start with what customers need to understand at each stage: why to subscribe, what makes a first purchase easier, how to get value after buying and when a return message is actually relevant. This makes lifecycle email, campaign planning and segmentation work together instead of competing for attention.</p><h2>Five parts of a durable ecommerce email program</h2><ol><li><strong>Permission and list growth.</strong> Give visitors a clear reason to subscribe, then make the welcome experience deliver on that promise.</li><li><strong>Lifecycle automation.</strong> Map the welcome, browse, cart, post-purchase and win-back moments before adding more sends.</li><li><strong>Campaign planning.</strong> Connect launches, offers and seasonal moments to one useful calendar rather than isolated promotions.</li><li><strong>Segmentation.</strong> Use customer context—such as product interest, purchase stage and engagement—to make the message more relevant.</li><li><strong>Measurement and learning.</strong> Decide what each message should achieve, then use the result to refine the next test.</li></ol></div></section>
      <section className="section section-border"><div className="container"><div className="section-heading"><p className="eyebrow">Related services</p><h2>Put the strategy into practice.</h2></div><div className="service-cards"><Link className="service-card" href="/services/klaviyo-email-marketing"><p className="eyebrow">Klaviyo agency</p><h2>Klaviyo email marketing</h2><p>Strategy, campaigns, segmentation and design for ecommerce retention.</p><span>Explore service →</span></Link><Link className="service-card" href="/services/shopify-email-marketing"><p className="eyebrow">Shopify email marketing</p><h2>Shopify retention strategy</h2><p>Email, automation and SMS planning built around your store.</p><span>Explore service →</span></Link><Link className="service-card" href="/services/email-automation-flows"><p className="eyebrow">Lifecycle automation</p><h2>Email automation flows</h2><p>Customer journeys for the moments that matter after sign-up.</p><span>Explore service →</span></Link></div></div></section>
      <section className="section faq-wrap"><div className="container"><div className="section-heading centered"><p className="eyebrow">Frequently asked questions</p><h2>Clear answers for ecommerce teams.</h2></div><div className="service-faqs">{faqs.map((faq) => <section className="service-faq" key={faq.question}><h3>{faq.question}</h3><p>{faq.answer}</p></section>)}</div></div></section>
    </article></main>
  </>;
}
