export const caseStudyOverviews: Record<string, string[]> = {
    'Aussies Merch': ['Aussies Merch creates fan merchandise for Australian sports supporters, with a range built around team pride and match-day culture.', 'Build the essential lifecycle flows so new subscribers, shoppers and customers receive relevant follow-up without depending only on one-off sends.', 'The flow setup generated more than 13% of total revenue. Overall attributed email revenue reached 33.98% of total revenue.'],
    HardBody: ['HardBody is a fitness brand built for people who care about strength, training and performance-led gear.', 'Set up campaign emails that give product drops, offers and collections a clear story, while keeping the brand tone direct and high-impact.', 'Email campaigns generated 31.1% of total store revenue for the reporting period shown in the supplied Omnisend dashboard.'],
    'Linen Tales': ['Linen Tales is a home and lifestyle brand known for considered linen pieces across bedding, dining and everyday living.', 'Build the full email setup - lifecycle flows, campaigns and supporting creative - so every customer touchpoint feels connected to the brand.', 'The complete email program generated 36.9% of total revenue in the supplied Omnisend reporting period.'],
    Twinky: ['Twinky helps parents shop practical products for everyday family life, from newborn essentials to travel and feeding items.', 'Create both the lifecycle flows and campaign calendar so the brand can support customers at the right stage of their parenting journey.', 'Email generated 29.47% of total revenue. Flows contributed 90.11% of attributed email revenue, supported by campaign activity.'],
    'Vape At Door': ['Vape At Door is an ecommerce retailer offering vape kits, flavours and accessories to a fast-moving customer base.', 'Create campaign emails with clearer creative direction and stronger conversion focus for promotional moments and product launches.', 'Campaign email generated 30.23% of total revenue, with £34,862.58 in attributed revenue in the supplied Klaviyo report.'],
    'US Boot': ['US Boot makes American-made work boots for customers who value durable, practical footwear.', 'Build the flows, campaign support and capture system needed to turn attention from a major media feature into a lasting email channel.', 'After implementation, email generated 15.06% of total revenue, with $8,419.28 in attributed revenue for the shown period.'],
    PopUpTee: ['PopUpTee creates pop-culture apparel for fans who want bold, wearable references to the worlds they enjoy.', 'Set up the key lifecycle flows and campaign emails while keeping every send visually distinctive and easy to shop.', 'Email generated 14.15% of total revenue, with $1,284.60 in attributed revenue in the supplied Klaviyo report.']
  };
